### ISSUE TITLE
responzivni design 

### ISSUE THREAD

**Issue by ViktoriaAndr** [VendulaKonecna/sluzby#1]
Ahoj,
máš responzivný design na tri veľkosti obrazovky, ale zadané to media query viackrát na rovnakú veľkosť. Prehľadnejší by bol kód pod sebou pre jednu veľkosť @media screen.

**Comment by VendulaKonecna** [comment]
Ahoj, já jsem to právě pochopila, tak že by se měla media query psát takhle jednotlivě. :-O

**Comment by ViktoriaAndr** [comment]
ale prečo tam máš viackrat media query na @media screen and (min-width: 1100px), atď?

**Comment by VendulaKonecna** [comment]
Omlouvám se , ale já tedy asi nechápu, jak by to mělo být. 
Co jsme dostaly komentované řešení  u projektu Recepty, tak to tak Luděk taky má.  I teď z lekcí Sassu u zanořování jsem pochopila, že se nastyluje komponenta pro mobil, pak pokud je potřeba, se udělá media query pro tablet a desktop a pak se zase nastyluje další část pro mobil ... atd...

**Comment by ViktoriaAndr** [comment]
```
@media screen and (min-width: 640px) {
    .container {
        max-width: 770px;
    } 
 .travels-image {
        max-width: 400px;
        height: 330px;
        margin: 0 auto 40px auto;
    }  
 .text-odstavec {
        max-width: 550px;
        margin: 0 auto 30px auto;
    }
.tlacitka {
        display: flex;
        justify-content: center;
        gap: 20px;
    }
    .tlacitko {
        margin: 0;
    }
    .dobrodruzstvi {
        margin-bottom: 0;
    }
.sluzby {
        display: flex;
        gap: 20px;
        max-width: 770px;
        margin-bottom: 80px;
    }
    .nabidka {
        flex: 1 1 calc(100% / 3);
        flex-direction: column;   
        padding: 40px 20px;
        margin: 0;
    }
    .nabidka-ikona {
        padding: 0 0 20px 0;
    }
    .nabidka p {
        text-align: center;
    }
    .nabidka:nth-child(3n) {
        margin-bottom: 0;
    }
}
```
Všetky classy/elementy ide nahádzať pod seba takto, ty to tam máš pre 640px 5krát
